### ISSUE TITLE
Arquivamento de processos

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#100]
### Criar opção de arquivamento de processos

- [x] Data de arquivamento
- [x] Observações do arquivamento
- [x] Ao listar processos não deixar os arquivados aparecerem
- [x] No filtro, incluir opção para listar o arquivamento

**Comment by AlexandreFerreiraRJ** [comment]
Fazendo

**Comment by AlexandreFerreiraRJ** [comment]
Feito

**Comment by AlexandreFerreiraRJ** [comment]
Ajustado o bug do Show depois do Arquivamento.

Issue → https://github.com/alerj/procuradoria/issues/148

**Comment by AlexandreFerreiraRJ** [comment]
Feito
