### ISSUE TITLE
Importação - Excel Normalizada

### ISSUE THREAD

**Issue by AlexandreFerreiraRJ** [alerj/procuradoria#147]

**Comment by AlexandreFerreiraRJ** [comment]
@BMasquio e eu vamos fazer.

**Comment by AlexandreFerreiraRJ** [comment]
Done it

**Comment by AlexandreFerreiraRJ** [comment]
Ajustado, @antonioribeiro 
[Tribunais - Importação.docx](https://github.com/alerj/procuradoria/files/1749644/Tribunais.-.Importacao.docx)

**Comment by antonioribeiro** [comment]
Ainda não terminou, mas tá quase, então já vou fechando.
