### ISSUE TITLE
Adicionar cargo e lotação do juiz no select de juizes

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#155]
![image](https://user-images.githubusercontent.com/3182864/35749057-6b97068c-0837-11e8-9564-78e9bb640c59.png)

**Comment by AlexandreFerreiraRJ** [comment]
@orlandovinicius1987 e eu terminamos essa issue.

**Comment by AlexandreFerreiraRJ** [comment]
Feito

**Comment by orlandovinicius1987** [comment]
Feito
