### ISSUE TITLE
Substituir todos os espaços em branco por N/C

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#156]
Em algumas tabelas estão ficando linhas nulas ou com espaço em branco. Trocar tudo por N/C.

**Comment by antonioribeiro** [comment]
Possivelmente será resolvido quando fizermos a importação do banco normalizado: https://github.com/alerj/procuradoria/issues/147

**Comment by BMasquio** [comment]
Em andamento.

**Comment by BMasquio** [comment]
Feito e já abri o Pull Request.
