### ISSUE TITLE
Personalizar os nomes dos campos na validação

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#157]
Local -> /procuradoria/resources/lang/pt_BR/validation.php

**Comment by AlexandreFerreiraRJ** [comment]
A partir da linha 119

Exemplos:

    'attributes'           => [
        'tipo_prazo_id'               => 'Tipo Prazo',
]

**Comment by BMasquio** [comment]
Em andamento.

**Comment by BMasquio** [comment]
Feito e já enviei o Pull Request.
