### ISSUE TITLE
Problema com alinhamento de campos no form de Processos

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#159]
É um problema do Select2 com o Bootstrap, criei uma issue lá no repositório deles: https://github.com/select2/select2/issues/5214

![image](https://user-images.githubusercontent.com/3182864/35750819-69657e92-083d-11e8-8d1f-06f43a9ce91c.png)

**Comment by BMasquio** [comment]
![image](https://user-images.githubusercontent.com/15174854/66414605-24b7b780-e9d0-11e9-8474-076469e7d8cc.png)

Já está consertado
