### ISSUE TITLE
Criação de testes

### ISSUE THREAD

**Issue by BMasquio** [alerj/procuradoria#187]
Tribunais
- [x] Insere e checa se foi inserido
- [x] Validações dos campos
- [x] Alterações
- [x] Busca

Juízes
- [x] Insere e checa se foi inserido
- [x] Validações dos campos
- [x] Alterações
- [x] Busca

Processos
- [x] Insere e checa se foi inserido
- [x] Validações dos campos
- [x] Alterações
- [x] Busca

Andamentos
- [x] Insere e checa se foi inserido
- [x] Validações dos campos
- [x] Alterações
- [x] Busca

Tags
- [ ] Busca

Apensos
- [x] Insere e checa se foi inserido
- [x] Validações dos campos
- [x] Alterações

Leis
- [ ] Insere e checa se foi inserido
- [ ] Validações dos campos
- [ ] Alterações

Ações
- [x] Insere e checa se foi inserido
- [x] Validações dos campos
- [x] Alterações

Users
- [x] Validação do email pessoal
- [x] Alterações

Revision
- [ ]  Insere

**Comment by AlexandreFerreiraRJ** [comment]
![image](https://user-images.githubusercontent.com/4698779/36399107-22a22f7c-15a9-11e8-9f45-b7627fdfc91d.png)

Estou com esse erro.

**Comment by antonioribeiro** [comment]
@AlexandreFerreiraRJ , vou precisar olhar o código pra ajudar nisso...

**Comment by BMasquio** [comment]
Estou tendo o mesmo erro.

**Comment by BMasquio** [comment]
Fazendo os testes de Processos

**Comment by BMasquio** [comment]
Fechando a issue, pois dividi em outras novas

#436 #437 #438
