### ISSUE TITLE
Criar lista para visualização de usuários

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#195]
Apenas uma tabela com a lista, para que possamos consultar.

- [x] Opção de menu
- [x] Lista de usuários
- [x] Botão para habilitar/desabilitar usuário
- [x] Não deixar usuário desabilitado usar o sistema

**Comment by AlexandreFerreiraRJ** [comment]
Done it, @antonioribeiro

**Comment by antonioribeiro** [comment]
Acrescentar botao para desabilitar/habilitar usuario

**Comment by AlexandreFerreiraRJ** [comment]
Did it!

**Comment by antonioribeiro** [comment]
"Não deixar usuário desabilitado usar o sistema" Também?
