### ISSUE TITLE
Campo de pesquisa de Andamentos

### ISSUE THREAD

**Issue by BMasquio** [alerj/procuradoria#198]
A pesquisa não está funcionando caso se pesquise pelos campos:

- Processo

- Tipo de andamento

- Tipo de entrada

- Tipo de prazo

- Data prazo

- Data de entrega

Não estão sendo carregados os relacionamentos para pesquisar.

**Comment by antonioribeiro** [comment]
Pesquisa na home?

**Comment by BMasquio** [comment]
Na pesquisa de Andamentos. Já corrigi e abri um Pull Request.
