### ISSUE TITLE
Criar andamento de "Recebimento do processo"

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#225]
Ao gravar um processo novo

- [x] Solicitar a data de recebimento
- [x] Criar tipo de andamento "Recebimento"
- [x] Depois de gravar criar o andamento relacionado ao processo
- [x] Criar data do recebimento também no process, toda vez que a data do recebimento do andamento for alterada, alterar esta data também
- [x] Não deixar incluir mais de um andamento com tipo "Recebimento"

**Comment by orlandovinicius1987** [comment]
Feita
