### ISSUE TITLE
Informação sobre o processo no "Site Alerj"

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#244]
- [x] Criar campos na tabela de processo
- site_alerj (boolean)
- site_alerj_link
- [x] Criar campos no form de processo
- [x] Filtro avançado

**Comment by BMasquio** [comment]
Fazendo.

**Comment by BMasquio** [comment]
Ainda fazendo Filtro avançado.

**Comment by BMasquio** [comment]
Feito
