### ISSUE TITLE
Não é possivel dar um dump and Die no request

### ISSUE THREAD

**Issue by orlandovinicius1987** [alerj/procuradoria#272]
Ao tentar fazer um dd no request, acontece o seguinte erro:

Undefined class constant 'PragmaRX\Version\Package\Version::DEFAULT_FORMAT'

![image](https://user-images.githubusercontent.com/20132028/37542709-e290d4b2-293d-11e8-94b1-5761240722cf.png)

**Comment by antonioribeiro** [comment]
Não consegui reproduzir...

**Comment by antonioribeiro** [comment]
Tá resolvido, basta dar um composer install.
