### ISSUE TITLE
Adicionar campos de notificação na tabela users

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#274]
- [ ] all_notifications (boolean)
- [ ] never_notify (boolean)
- [ ] Adicionar ao formulário de edição de usuários
- [ ] Configurar notificações para usar estes campos

**Comment by BMasquio** [comment]
Feito

 all_notifications (boolean)
 no_notification (boolean)
 Adicionar ao formulário de edição de usuários
