### ISSUE TITLE
Fix "Limpar Pesquisa Avançada" e Criação do seu Teste

### ISSUE THREAD

**Issue by AlexandreFerreiraRJ** [alerj/procuradoria#282]
- [x] Fix "Limpar Pesquisa Avançada

- [ ] Criação do seu Teste

**Comment by AlexandreFerreiraRJ** [comment]
Feito →  Fix "Limpar Pesquisa Avançada

**Comment by AlexandreFerreiraRJ** [comment]
Feito → Fix "Limpar Pesquisa Avançada"

**Comment by BMasquio** [comment]
Criada issue só pro teste #439
