### ISSUE TITLE
Buscar número de processo sem pontuação

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#355]
Quando cometem um erro de pontuação não conseguem mais encontrar um processo pelo número

**Comment by AlexandreFerreiraRJ** [comment]
Feito tmb

**Comment by AlexandreFerreiraRJ** [comment]
![image](https://user-images.githubusercontent.com/4698779/46565861-0154bb00-c8eb-11e8-95a0-14bd5eeb02d0.png)
