### ISSUE TITLE
Problemas na busca

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#396]
- [x] Os termos de busca têm ser buscados separadamente, mas tem que ser E e está OU, assim ele está juntando e não filtrando

- [x] Não está localizando termos acentuados, Brazão, por exemplo

**Comment by AlexandreFerreiraRJ** [comment]
- [ ]  Os termos de busca têm ser buscados separadamente, mas tem que ser E e está OU, assim ele está juntando e não filtrando

- [ ]  Não está localizando termos acentuados, Brazão, por exemplo

**Comment by AlexandreFerreiraRJ** [comment]
Feito!
