### ISSUE TITLE
Ao digitar processo, usar regex pra procurar número e data

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#404]
Testar com 7.898 e 7898

Problema recorrente que não conseguimos resolver.

- [x] Busca
- [x] Highlight

**Comment by AlexandreFerreiraRJ** [comment]
Testar com 7.898 e 7898

Problema recorrente que não conseguimos resolver.

- [x]   Busca
- [ ]   Highlight

**Comment by AlexandreFerreiraRJ** [comment]
![image](https://user-images.githubusercontent.com/4698779/54161494-0e914b00-4431-11e9-9fb9-c8ca874fc951.png)

**Comment by AlexandreFerreiraRJ** [comment]
![image](https://user-images.githubusercontent.com/4698779/54719635-260cba00-4b3c-11e9-8703-755e4466c344.png)
