### ISSUE TITLE
Busca automática por digitação está confundindo o usuário

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#407]
Está lento, muito lento, então isso acaba confundindo aquele usuário que digita uma parte e depois outra do texto a ser buscado.

- [x] Paginar resultado (25 por página, inicialmente)
- [x] Informar quantidade total de registros (430) e quantidade de registros filtrados (25)
- [x] Desligar a busca automática
- [x] Buscar ao teclar enter
- [x] Verificar se o botão de buscar continua funcionando para busca manual

**Comment by AlexandreFerreiraRJ** [comment]
- [ ]  Paginar resultado (25 por página, inicialmente)
- [ ]   Informar quantidade total de registros (430) e quantidade de registros filtrados (25)
- [ ]   Desligar a busca automática
- [ ]   Buscar ao teclar enter
- [ ]   Verificar se o botão de buscar continua funcionando para busca manual

**Comment by AlexandreFerreiraRJ** [comment]
- [x]

**Comment by AlexandreFerreiraRJ** [comment]
Feito!
