### ISSUE TITLE
Validações dos inputs e selects

### ISSUE THREAD

**Issue by AlexandreFerreiraRJ** [alerj/procuradoria#93]
Os obrigatórios foram definidos na reunião do dia 12-03-2018:

- [x] Número judicial
- [x] Autor
- [x] Réu

--------------------------------------------

Tamanho mínimo e máximo;
obrigatórios e opcionais;
domínios ...

Alguns são intuitivos , outros teremos que levantar com a usuária.

**Comment by antonioribeiro** [comment]
No geral a maioria é simples e fácil de inferir, com exceção, do numero_judicial:

https://www.conjur.com.br/2009-jan-23/cnj-define-padrao-numeracao-processos-todos-tribunais

**Comment by AlexandreFerreiraRJ** [comment]
@orlandovinicius1987 e @BMasquio  ajustei o bug da validação

**Comment by AlexandreFerreiraRJ** [comment]
https://laravel.com/docs/5.5/validation#available-validation-rules

**Comment by AlexandreFerreiraRJ** [comment]
Olá @antonioribeiro  , eu ajustei somente o bug que nós encontramos.
Essa demanda de Validar os campos está uma parte com @BMasquio  e outra parte com o @orlandovinicius1987  .

Fiz esse Pull Request, para que os rapazes pudessem agora testar e implementar a validação.
Já que com o Bug estava impedindo a continuidade do trabalho.
Entendeu ?

**Comment by AlexandreFerreiraRJ** [comment]
Done!

**Comment by AlexandreFerreiraRJ** [comment]
@antonioribeiro vc consegue fechar ? Ou somente o dono (neste caso, eu) ?
